myweb/message/urls.py
from django.urls import path
from . import views

app_name = 'message'
urlpatterns =[
    path('' , views.index , name = 'index'),
    path('messagedetail/<int:message_id>/' , views.messagedetail , name = 'messagedetail'),
    path('login/' , views.login , name = 'login'),
    path('register/' , views.register , name = 'register'),
    path('userinterface/' , views.userinterface , name = 'userinterface'),
]  

myweb/myweb/urls.py
from django.contrib import admin
from django.urls import path , include
from myweb.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('message/', include('message.urls')),
    path('' , home),
]

myweb/message/models.py
from django.db import models


class User(models.Model):
    username = models.CharField(max_length = 20)
    password = models.CharField(max_length = 20)
    creation_time = models.DateTimeField()

    def __str__(self):
        return self.username

class Message(models.Model):
    message_user = models.CharField(max_length = 20)
    message_text = models.CharField(max_length = 20)
    message_contect = models.CharField(max_length = 100)
    message_time = models.DateTimeField()

    def __str__(self):
        return self.message_text

myweb/message/views.py
from django.shortcuts import render , redirect
from django.http import HttpResponse
from message.models import User , Message
from django.utils import timezone


def index(request):
    message_list = Message.objects.all()


    context = {
        'message_list' : message_list,
    }

    return render(request,'message/index.html' , context)

def login(request):
    #message = request.POST.get('message' , '')
    #message = request.POST['message']
    if request.method == "POST":
        login_username = request.POST['username']
        login_password = request.POST['password']
        user_list = User.objects.all()
        b = True
        for a in user_list:
            if login_username == a.username:
                b = False
                if login_password == a.password:
                    #登录成功使用session记录登录用户的id
                    #用户处于登录状态，退出浏览器后失效
                    request.session['is_login'] = True
                    request.session['user_id'] = a.id
                    request.session.set_expiry(0)
                    return redirect('/message/userinterface/')
                else:
                    #错误：提示密码错误
                    context = {
                        'text' : '密码错误！！！',
                    }
                    return render(request , 'message/login.html' , context)
        if b:
            #错误：提示账号不存在
            context = {
                'text' : '该账号不存在，请先注册！',
            }
            return render(request , 'message/login.html' , context)
    else:
        return render(request , 'message/login.html')

def register(request):
    if request.method == "POST":
        register_username = request.POST.get('username' , '')
        register_password = request.POST.get('password' , '')
        #判断条件
        c = True
        #1、不能注册名字相同的账号

        user_list = User.objects.all()
        username_list = []
        for b in user_list:
            username_list.append(b.username)
        for d in username_list:
            if register_username == d:
                c = False

        #符合规定c为True，成功注册
        if c:
            a = User()
            a.username = register_username
            a.password = register_password 
            a.creation_time = timezone.now()
            a.save()
            context = {
                'text' : '你已经注册成功，即可登录!',
            }
            return render(request , 'message/login.html' , context)
        #不符合规定重新注册
        else:
            context = {
                'text' : '你输入的账号已经存在，请你换个账号名！！！',
            }
            return render(request , 'message/register.html' , context)
    else:
        return render(request , 'message/register.html')


def userinterface(request):
    if request.session['is_login']:
        #写留言的情况
        if request.method =="POST":
            #确认用户的id
            user_id = request.session['user_id']
            username = User.objects.get(id = user_id)
            #获取该用户的留言
            user_message_list = Message.objects.filter(message_user = username)

            #填写留言
            a = Message()
            a.message_text = request.POST.get('message_text' , '')
            a.message_contect = request.POST.get('message_contect' , '')
            a.message_user = User.objects.get(id = user_id)
            a.message_time =timezone.now()
            a.save()

            context = {
                'user_message_list' : user_message_list,
            }
            return render(request , 'message/userinterface.html' , context)
        else:
            #确认用户的id
            user_id = request.session['user_id']
            username = User.objects.get(id = user_id)
            #获取该用户的留言
            user_message_list = Message.objects.filter(message_user = username)

            context = {
                'user_message_list' : user_message_list,
            }
            return render(request , 'message/userinterface.html' , context)
    else:
        context = {
            'error' : '你还没有登陆，请先登录！',
        }
        return render(request , 'message/login.html' , context)

def messagedetail(request , message_id):
    message = Message.objects.get(id = message_id)
    context = {
        'message' : message,
    }
    return render(request , 'message/messagedetail.html' , context)

myweb/myweb/views.py
from django.http import HttpResponse
from django.shortcuts import render

def home(request):
    return render(request , 'message/mainindex.html')

myweb/message/templates/message/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Index</title>
    <style>
        div{
            text-align: center;
            font-size: 300%;
            color: rgb(255, 0, 0);
            }
        div.text{
            font-size: 300%;
            text-align: center;
            color: rgb(9, 255, 0);
        }
        table{
            color: blue;
            font-size: 200%;
        }
    </style>
</head>
<body>
    <div>欢迎你来到***的第一个应用，这里是主页面</div>
    <div class="text">
        <a href="/message/login">登录</a><br>
        <a href="/message/register">注册</a>
    </div>
    <table border="1">
        <tr>
            <td>用户名</td>
            <td>留言标题</td>
            <td>留言时间</td>
        </tr>
        {% for c in message_list %}
        <tr>
            <td>{{c.message_user}}</td>
            <td>{{c.message_text}}</td>
            <td>{{c.message_time}}</td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>

myweb/message/templates/message/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
</head>
<body>
    <div>这里是登录界面</div>
    <form action="/message/login/" method="post" autocomplete="off">
        <div>账号</div>
        <input type="text" name="username"><br>
        <div>密码</div>
        <input type="text" name="password"><br>
        <input type="submit" value="提交">
        {% csrf_token %}
    </form>
    <div>{{text}}</div>
    <a href="/message/register/">注册</a>
</body>
</html>

myweb/message/templates/message/mainindex.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>index</title>
</head>
<body>
    <b>欢迎来到***项目</b>
    <div>点击按钮进入到第一个应用</div>
    <a href="/message/">留言</a>
</body>
</html>

myweb/message/templates/message/messagedetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Messagedetail</title>
    <style>
        div{
            color: blue;
        }
        div.detail{
            color: red;
            border-style:solid;
            width: 160px;
            height:60px;
            font-size: 250%;
            margin-top: 50px;
            margin-left: 700px;
        }
        div.tect{
            color: blueviolet;
            border-style:solid;
            width:80%; 
            margin-left: 10px;
            font-size:150%;
        }
        div.contect{
            color: blueviolet;
            border-style:solid;
            width:80%; 
            height: 400px;
            margin-left: 10px;
            font-size:150%;
        }
    </style>
</head>
<body>
    <div>欢迎来到留言的详情</div>
    <div class="detail">留言详情</div>
    <div class="tect">{{message.message_text}}</div>
    <div class="contect">{{message.message_contect}}</div>
    <div class="time">{{message.message_time}}</div>
</body>
</html>

myweb/message/templates/message/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Register</title>
</head>
<body>
    <div>这里是注册界面</div>
    <form action="/message/register/" method="POST" autocomplete="off">
        <div>请输入你的账号</div>
        <input type="text" name="username"><br>
        <div>输入密码</div>
        <input type="text" name="password"><br>
        <input type="submit" value="提交">
        {% csrf_token %}
    </form>
    <div>{{text}}</div>
    <a href="/message/login/">返回</a>
</body>
</html>

myweb/message/templates/message/userinterface.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>User</title>
</head>
<body>
    <div>这里是用户主界面</div>
    <table border="1">
        <caption>你发布的留言</caption>
        <thead>
            <tr>
                <th>留言标题</th>
                <th>发布时间</th>
                <th>进行操作</th>
            </tr>
        </thead>
        <tbody>
            {% for a in user_message_list %}
            <tr>
                <th>{{a.message_text}}</th>
                <th>{{a.message_time}}</th>
                <th><a href="{% url 'message:messagedetail' a.id %}">详情</a></th>
            </tr> 
            {% endfor %}
        </tbody>
    </table><br>
    <form action="/message/userinterface/" method="POST" autocomplete="off">
        <div>发布你的留言</div>
        <input type="text" name="message_text"><br>
        <input type="text" name="message_contect">
        <input type="submit" value="提交">
        {% csrf_token %}
    </form>
</body>
</html>